# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    
    runs-on: windows-latest
    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
       - uses: microsoft/setup-msbuild@v1.0.1
  
       - name: Build Release 
         run: msbuild /p:Configuration=Release -maxCpuCount

       - name: Upload Release Build
         uses: actions/upload-artifact@v2
         with:
          name: Build Release
          path: x64\Release\
          
          
       - name: Build Debug 
         run: msbuild /p:Configuration=Release -maxCpuCount

       - name: Upload Debug Build
         uses: actions/upload-artifact@v2
         with:
          name: Build Release
          path: x64\Debug\
